apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-backend
  labels:
    app: inference-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference-backend
  template:
    metadata:
      labels:
        app: inference-backend
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: inference-backend
        image: ghcr.io/hitchai-app/inference-backend:prod-625d7f724613d49cefc7e28e425ab69210058ea9
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://valkey:6379"
        - name: CENTRIFUGO_URL
          value: "http://centrifugo:8000"
        - name: LITELLM_URL
          value: "http://litellm:4000"
        - name: LITELLM_API_URL
          value: "http://litellm:4000"
        - name: LITELLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: litellm-secrets
              key: master-key
        - name: PLATFORM_API_URL
          value: "http://platform-backend:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
