---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-api-secrets
  namespace: steady-stage
spec:
  encryptedData:
    api-key: AgCmBUFvR2ZUmvrOIcweQFTPajnFGJJgWDc1+gfwkGJGZL3qZENTQsIc4YG2Dtz2ZYkcwv3OhlJbDIqr6gynnNcHrSi7pZ+a5FM4pbcB8e17F2biG5LxR8GzK24rEtKI67UxG+wckySHmJM//67kS5IefhJdQBHnPICbCvYWaZESifOfMbuHwVum5u5WokFYEghMd/H51sRVcfdqjCdX/YxN6vQEhA4vVMlWVKzGy51vMN62ViImUDr4MYeyz0iCojJL33vGRl5fnKnCO3Px4BIin+dBTzINjhUfhb47a6ogsNFhXPZT9IjQZzscAmsXX2OYxGefTvUfe2RV+6hIp6t2Am3hoyryLFimGEFQUTY2pLu5KK62Yf1zvNwMTqKD9PhltSBwdbTpyl+YkcrRsXkKDn+AeJeBfOKZkQg5hTN8jk54AT9nKDvPAhfEuer7Y4Gar3BMSPcz7mSSz9A0p8olpedAwkz3z2/j/fEAS5dC63u/1hoxR6TfDmze8We1gSrH/xql2/kAnx0Y2uxQJrBnoWmlzAT4LZ3JnTX9h+dQzsh6fh/J1w9750M59qYP6wQlaDDajB0A+yA9xD6lZsuQdagVv2klEpkO0Qaopma6tEetH8qZl/CVW6LxqIHZQbzkqicaGXm33mSIJkRzhJ9H09lMXyna0AQgPhcKvZAr38QkenC/7Bya+mLqXibvE3fmoCmcmI47+ulLU/Gic9b+A6j3WnuKSV7oNJyk4VON2X1qMkMWpPrzCbbkwA==
  template:
    metadata:
      creationTimestamp: null
      name: platform-api-secrets
      namespace: steady-stage
