apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-backend
  labels:
    app: platform-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-backend
  template:
    metadata:
      labels:
        app: platform-backend
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: platform-backend
        image: ghcr.io/hitchai-app/platform-backend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-platform-user
              key: uri
        - name: REDIS_URL
          value: "redis://valkey:6379"
        - name: CENTRIFUGO_URL
          value: "http://centrifugo:8000"
        - name: CENTRIFUGO_API_KEY
          valueFrom:
            secretKeyRef:
              name: centrifugo-secrets
              key: api-key
        - name: CENTRIFUGO_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: centrifugo-secrets
              key: admin-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
