apiVersion: batch/v1
kind: Job
metadata:
  name: platform-backend-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: migrate
        image: ghcr.io/hitchai-app/platform-backend:prod-38c90d9cbdf564b68f78b250b1f3f4ff15eb9ca7
        command: ["node", "dist/db/migrate.cli.js"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-platform-user
              key: uri
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
