apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ui
  labels:
    app: dev-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-ui
  template:
    metadata:
      labels:
        app: dev-ui
    spec:
      containers:
      - name: dev-ui
        image: ghcr.io/hitchai-app/dev-ui:prod-0c4d2112ab8139caac21585dd292705062586aea
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://platform-backend:3000"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://centrifugo:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
