apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-backend
  labels:
    app: inference-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference-backend
  template:
    metadata:
      labels:
        app: inference-backend
    spec:
      containers:
      - name: inference-backend
        image: ghcr.io/hitchai-app/inference-backend:prod-da6d5ee6ca0396a3d23808b06f91ea0fbced04bf
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: inference-db-credentials
              key: uri
        - name: REDIS_URL
          value: "redis://valkey:6379"
        - name: CENTRIFUGO_URL
          value: "http://centrifugo:8000"
        - name: LITELLM_URL
          value: "http://litellm:4000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
