apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/hitchai-app/platform-backend
    newTag: prod-acaa4ca88732b24d25b117f58726cae4eca41495
