---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: steady-stage
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBVF0HId0egKPaQBTRmhSC2KBMaS1xSkv952cVRlaPFUqYcb0mkJMQcxSiV5KlIJm02+ioHB+F4r4B9ybO+ywGe323r+4BG2J0DTBmxfSHIgeFad8/SCVe2Gb18F14BLR8p5BQzSbPyOrecPILVJQYA8HXUjj4A0g/nCVdF8FUmbnk+5UrfmyNcdY468upQX5FbSDlgwPtdhcAAiNPbzviKF89cNNTYgM/w++5MRGnZSvKA0wJKDoZj3B2ORPGDzC/XWcADn962hzeWN8OS/8lBvk+nvPOubqXRcGT0rXSdO48C6B/ZhF+LNj7bcxnWkbMn7Id9m6c3LACl5U13iYO6ZdR1gXQNilDJwqezfsr8ReuUW/7ZjJB/jNKKOGwrR1YrSELckURoQV0FhuDrFEvKquicjY6/EtGaMtxay2rp7raLizog/kq7Ul2XytgqGgNYocPNZHtC+7kVjxV36ZWlfmD6cSnpGPImbh6Z/OrxSW6GcO7YYjpyz7gPAiqF8ITOu9hcX9H4bQDwP5bqxiutRulRelDS5mZn7PO1JwZykq8N4O5q982aMzVmYallLxaeP0c79qvg3+rHbd5/zcx9GTpsnZoqKF42H7ATpzrsthOKEg+6/dTeQeE7WAh00Qw+VOEu1o2W4JA5Sq1+1j6okV7xIzOJbj5QQVgF4bzut0tcK4q4aLohYeCGphAwh/m3hsL4CbEFSzsWTwMElyFvOcjc2yKQCOCPgUmdvCuBbFgyy11cBeg/utmc+U9werYzzGjYKR3r8eQjORSaDM1GxOWq2E7X12zHOl6sB2qL9+4tbsTJV1pr0+ag3E2elZTI/jpUg0OYvpUx44MPRlSAKOO0d51z6HBR/nf6SX5i4wcGgC36zb/5cBdkEBk2QgWHfgBq9f+vw+KvOT3t0fFBTxuHa/61EIJsrdBfj1Qellk=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: steady-stage
    type: kubernetes.io/dockerconfigjson
