apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      work_mem: "16MB"

  storage:
    size: 20Gi
    storageClass: single-replica

  managed:
    roles:
    - name: litellm_user
      ensure: present
      login: true
      createdb: false
      createrole: false

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://cloudnativepg-backups/steady
      s3Credentials:
        accessKeyId:
          name: backup-s3-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: backup-s3-credentials
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
        encryption: AES256
        maxParallel: 2
      data:
        compression: gzip
        encryption: AES256
        jobs: 2

  monitoring:
    enablePodMonitor: true
