apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/hitchai-app/inference-backend
    newTag: stage-ea3e6536f60108b8f623aa8de7b0d3fdcda76ef7
