apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ui
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: dev-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-ui
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-12T14:30:00Z"
      labels:
        app: dev-ui
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: dev-ui
        image: ghcr.io/hitchai-app/dev-ui:stage-eb723610c57abdd782a3d5e80878a5c8cda5bc72
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
