apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steady-stage

resources:
- configmap.yaml
- deployment.yaml
- centrifugo-secrets-sealed.yaml
- middleware.yaml
- ingress.yaml
