apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steady-prod

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 5Gi
  target:
    kind: StatefulSet
    name: valkey
