apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: steady-stage

resources:
- ../../base
- backup-s3-credentials-sealed.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/instances
      value: 1
    - op: replace
      path: /spec/storage/size
      value: 10Gi
    - op: replace
      path: /spec/backup/barmanObjectStore/destinationPath
      value: s3://cloudnativepg-backups/steady-stage
  target:
    kind: Cluster
    name: postgres
