apiVersion: v1
kind: Service
metadata:
  name: centrifugo
spec:
  selector:
    app: centrifugo
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 10000
    targetPort: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centrifugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centrifugo
  template:
    metadata:
      labels:
        app: centrifugo
    spec:
      containers:
      - name: centrifugo
        image: centrifugo/centrifugo:v6
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 10000
          name: grpc
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: centrifugo-secrets
              key: admin-password
        - name: ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: centrifugo-secrets
              key: admin-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: centrifugo-secrets
              key: api-key
        command:
        - centrifugo
        - --health
        args:
        - --admin_password=$(ADMIN_PASSWORD)
        - --admin_secret=$(ADMIN_SECRET)
        - --api_key=$(API_KEY)
        - --log_level=info
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
