apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: miniapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniapp
  template:
    metadata:
      labels:
        app: miniapp
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: miniapp
        image: ghcr.io/hitchai-app/miniapp:stage-a106a8ddd8d6bde8cd70b1522bdf39eca8c5ea19
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
