---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: steady-prod
spec:
  encryptedData:
    master-key: AgB8Mn6SfqOiR/b+LcuLOR5KVZlTfa+Hl+cNOuPowVoaBNPcGmuXecXF8ecih5IvKzpWvlBVIpFmFF59CsitHxIKqh96aTJqK4Gcd1Oa6PpIQRHrG2HE2moOAjmQth8m4NR+u3Pt3k7yF8MPhzz56fAQvgboFENx8Rnw2vbsXP2RGcpao0dfQ3XDZVsuNx6CzCknDKrBCJmfFqFmQ/AU9xO6namL3Bqr4MoyCfHZ04zTwh2RPPvyPtXQD29Sfoee76jdfaOxamff/+5K2jvi+YBTt0Aa2Yw6q+ajsvWWitwNcIJWMHZemXk9ig9yki2vr9bkeMTPZCNWnwS8u0C/TxkDY0xNcuJD+jgYOrg59h3lkk1dIpMEeTjmzJc9Fg4pLNYk9PQJ5ZBvHnU6kCvwda2qmIyW/+5UM8S0M+jrS0rfc0KQvEyIB8RxbAoAHTtRKoyeHOc+pT155IzGqK3u/QMOs2O6rXOX37qbCIwZPyl7W8E+nMNQ7ZZZ/B7EKvrAkHfUK3tOCxM6f0bccmKUAfcG0OiEaPcwI9nHMRieI19V4lz3tBhAT216SWPUmqgkiqbKHP+GVQayyWOMe6gKGOVOUlG4uyQfaM4dNNakSy/lYGAXgreUWUQCFIEGbwiUTTPVgvNBqhVqXnEH1qnj/t8D1P9so351wtqp+eU1ljL2H0SLwN5Pt1euf89cRe4dtaSYNoprZvjQ/AmLcE8Qoj3i6El8w11c46eS0qpp1bp0
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: steady-prod
