apiVersion: batch/v1
kind: Job
metadata:
  generateName: platform-backend-migration-
  annotations:
    # Run before the Deployment (which is wave "2")
    argocd.argoproj.io/sync-wave: "1"
    # Treat this as an ephemeral hook so ArgoCD creates a fresh Job each sync
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: platform-backend-migration
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: migrate
        image: ghcr.io/hitchai-app/platform-backend:latest
        command: ["node", "dist/db/migrate.cli.js"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-platform-user
              key: uri
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
