name: Update Image

on:
  repository_dispatch:
    types: [image_update]

permissions:
  contents: write    # Required to commit and push changes

jobs:
  update-manifest:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
          ref: master

      - name: Update image tag in environment overlay
        run: |
          SERVICE="${{ github.event.client_payload.service }}"
          IMAGE="${{ github.event.client_payload.image }}"
          ENVIRONMENT="${{ github.event.client_payload.environment }}"
          IMAGE_TAG="${IMAGE##*:}"
          OVERLAY_FILE="applications/${SERVICE}/overlays/${ENVIRONMENT}/kustomization.yaml"

          echo "Updating $SERVICE in $ENVIRONMENT environment"
          echo "New image: $IMAGE"

          if [ ! -f "$OVERLAY_FILE" ]; then
            echo "Overlay file not found: $OVERLAY_FILE"
            exit 1
          fi

          # Update image tag in overlay kustomization
          sed -i "s|newTag: .*|newTag: ${IMAGE_TAG}|" "$OVERLAY_FILE"

          # Show changes
          echo "=== Changes ==="
          git diff "$OVERLAY_FILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add applications/${{ github.event.client_payload.service }}/

          git commit -m "chore(${{ github.event.client_payload.service }}): update image

          Image: ${{ github.event.client_payload.image }}
          Environment: ${{ github.event.client_payload.environment }}
          Source commit: ${{ github.event.client_payload.commit }}
          Source branch: ${{ github.event.client_payload.branch }}"

          git push
