---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: steady-stage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    .dockerconfigjson: AgA5xAXQ5YhIzwxhVA/PT4UpYbq2HsRuO87MPZ0hV2XmVpUaTzzV6yJEAEh94O44tll1Cs3Y/jOh3H8LKDupz+icm7Q/8ehYGbHBGDdpM5DmXucD0I2aHtIJ9QYUik1/746l+dEeJKn3/lRKe9jHBkMRI/XLa/BQGTJQO/VDuceGm+cvqbbMW4YOr8W8W7FMglQ/AjwzyiEmTWWUtaqpRbLvWhRGUR+blDFP4U7g7tmj3ahwzwwy0kFOuBrIeIQ83snLQtMmlLi6cCwEzPHAXAsGZkGD+2Hlgd0wL5NADwwth5S20aw8H2GL82UK1mJQ3SZspsRq2ySjZeh1QZptWenBhdGNln7YT7fjNz3B2XqxWIyLQjoMol7rWuupZ5DJBvDntBaAot9Ex4mNyVnYfE+orhEvuy25cQTSEsvibHLsC6Opr4IxrFHKpL5QSuln6k95eOeckmRi/LJ48k/qCh9iodx4o1awEtj3v5nEhBthqOlMGWy3Cbxsweg6dHc3w77l5Ax6RRWNf/oUQxIgIlMdzy4g6cXMAtByCMBmAj2/4Z+uRUncaA7kFsykydZw8OSdNbFnaJCVNEum2DVbAm/5/zi1ZZef7yIxwEj8sSrj39CCW66JIug9aSW0DrWTsRlGB0p8s8BrN/X5mep3Ob5SOaWFcH3A+GkCHogPmTsh3Db57Z1dyaricklcH4L2K0ushz66EcIhd5YQCUahIrRl+HEUm3EKVMaphi/NZUq7PtqReZNIpyu9MuWooqhljZ97nbeGwuxyoIa72RaDuBMeNeN4houu2pfLONu68tEo5vvIZrvptLsGfNvaltuy5XL+a3IpqkZ0JyKPIY1z9HlZhVd1TpfqVAcfmEeF1Pd+1XRgz0gFkLJPifJTfCKtbtybMoLw0ADpINg2YsJceCgOHqPgmTA0XkeFAAkhdwmJ0AlXuGmoqEskUa7R4SnmyAsYc1Tw8Fq66HcsUuil3guGt/f/zsCfT61Pn43mG5ti6YrLgcXufVoa34go74tGxrUMmv9nMPjLtqFAgubOS58G4AhbeAe/+xXTLBgw+7ihn6bLyXCsILh4qMRpyIHVJwfdGHkUyVfsqnRflTeTj8wexw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: steady-stage
    type: kubernetes.io/dockerconfigjson
